swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Sensor
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /sensor_data:
    get:
      operationId: controller.get_node_sensor_data
      tags:
        - Sensor
      summary: Read the entire list of sensor data
      description: Read the sensor data
      responses:
        200:
          description: Successfully read sensor data list operation
          schema:
            type: array
            items:
              properties:
                node_id:
                  type: string
                sensor_id:
                  type: string
                time:
                  type: string
                value:
                  type: string
                migrated:
                  type: string
